use db_comercio;
alter table produtos add column categoria enum("Bebidas", "Doces", "Salgados", "Padaria", "Mercearia");
select * from produtos;
set SQL_SAFE_UPDATES = 0;
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Coca Cola 2L';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Conquista 2L';
UPDATE produtos SET categoria = 'Padaria' WHERE nome = 'Pão francês (Uni.)';
UPDATE produtos SET categoria = 'Padaria' WHERE nome = 'Pão de forma panco (500g)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Brahma lata 350ml (Uni.)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Skol lata 350ml (Uni.)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Antártica lata 350ml (Uni.)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Crystal lata 350ml (Uni.)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Caixinha de Crystal (12x)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Caixinha de Brahma (12x)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Caixinha de Skol (12x)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Caixinha de Antártica (12x)';
UPDATE produtos SET categoria = 'Bebidas' WHERE nome = 'Leite 1L';
UPDATE produtos SET categoria = 'Padaria' WHERE nome = 'Sonho de padaria (Creme e outros)';
UPDATE produtos SET categoria = 'Doces' WHERE nome = 'Rosca doce (Creme e outros)';
UPDATE produtos SET categoria = 'Salgados' WHERE nome = 'Coxinha';
UPDATE produtos SET categoria = 'Salgados' WHERE nome = 'Esfirra';
UPDATE produtos SET categoria = 'Salgados' WHERE nome = 'Salsicha empanada';
UPDATE produtos SET categoria = 'Mercearia' WHERE nome = 'Sabonete Granado';